### ISSUE TITLE
Any way to provide a custom specs?

### ISSUE THREAD

**Issue by bingqiao** [jasonkneen/TiCons-CLI#60]
This is mainly for the benefits of creating splash images of different sizes than defined in the specs.js for Android. Looking into the code, it seems there is no way to customize the specs.js.

Thanks

**Comment by FokkeZB** [comment]
Hi @bingqiao, great suggestion! I don't actively maintain this project anymore, but I do review PRs. So if you'd like to take a stab at it; go ahead!
