### ISSUE TITLE
Outdated deps - "primordials not defined"

### ISSUE THREAD

**Issue by igorsantos07** [jasonkneen/TiCons-CLI#67]
When trying to execute the main command under Node 12.19, a weird `primordials not defined` popped-up. It seems it's related to an internal dependency which is not compatible with Node 12+, the `graceful-fs` package. It's required directly by the package, but also by `configstore` and `update-notifier` (which is already in v5?).

These deps need some bumps so we can keep using the package in updated Node versions.

It seems that forcing the `package.json`'s `update-notifier` to `^5.0.0` and running `npm install` for each of those three outdated deps does the trick... at least to run `ticons icons`.

**Comment by antonioduran** [comment]
Hello @igorsantos07 . Thank you. You saved my day...

**Comment by ottopic** [comment]
updated into #70
